//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medit
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodePostal
    {
        public CodePostal()
        {
            this.Entreprises = new HashSet<Entreprise>();
            this.Travailleurs = new HashSet<Travailleur>();
        }
    
        public decimal Id_CodePostal { get; set; }
        public decimal Code { get; set; }
        public string Localite { get; set; }
    
        public virtual ICollection<Entreprise> Entreprises { get; set; }
        public virtual ICollection<Travailleur> Travailleurs { get; set; }
    }
}
