//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medit
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entreprise
    {
        public Entreprise()
        {
            this.TravEnts = new HashSet<TravEnt>();
        }
    
        public decimal Numero { get; set; }
        public string Denomination { get; set; }
        public string AdresseNum { get; set; }
        public string AdresseRue { get; set; }
        public string NumTel { get; set; }
        public decimal NbEmployeDebAnneeSoumis { get; set; }
        public decimal NbEmployeDebAnneeNon_Soumis { get; set; }
        public decimal Code_Secteur { get; set; }
        public decimal Id_Langue { get; set; }
        public decimal Id_CodePostal { get; set; }
        public string Adresse { get { return AdresseRue + ", " + AdresseNum; } }
        public string Adresse2 { get { if (CodePostal != null) return CodePostal.Code + " " + CodePostal.Localite; else return ""; } }
    
        public virtual CodePostal CodePostal { get; set; }
        public virtual Langue Langue { get; set; }
        public virtual ICollection<TravEnt> TravEnts { get; set; }
    }
}
