//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medit
{
    using System;
    using System.Collections.Generic;
    
    public partial class LangueProfession
    {
        public decimal Id_LangueProfession { get; set; }
        public decimal Id_Langue { get; set; }
        public decimal Code { get; set; }
        public string Denomination { get; set; }
    
        public virtual Langue Langue { get; set; }
        public virtual Profession Profession { get; set; }
    }
}
