//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medit
{
    using System;
    using System.Collections.Generic;
    
    public partial class Langue
    {
        public Langue()
        {
            this.Entreprises = new HashSet<Entreprise>();
            this.LangueProfessions = new HashSet<LangueProfession>();
        }
    
        public decimal Id_Langue { get; set; }
        public string Libelle { get; set; }
    
        public virtual ICollection<Entreprise> Entreprises { get; set; }
        public virtual ICollection<LangueProfession> LangueProfessions { get; set; }
    }
}
