//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medit
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profession
    {
        public Profession()
        {
            this.LangueProfessions = new HashSet<LangueProfession>();
            this.TravEnts = new HashSet<TravEnt>();
        }
    
        public decimal Code { get; set; }
    
        public virtual ICollection<LangueProfession> LangueProfessions { get; set; }
        public virtual ICollection<TravEnt> TravEnts { get; set; }
    }
}
