//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medit
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travailleur_NonSoumis
    {
        public decimal Id_TravEnt { get; set; }
    
        public virtual TravEnt TravEnt { get; set; }
    }
}
