//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medit
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travailleur
    {
        public Travailleur()
        {
            this.TravEnts = new HashSet<TravEnt>();
        }
    
        public decimal Id_Travailleur { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string NumTel { get; set; }
        public string AdresseNum { get; set; }
        public string AdresseRue { get; set; }
        public Nullable<decimal> NumDossierMedical { get; set; }
        public decimal Id_CodePostal { get; set; }
    
        public virtual CodePostal CodePostal { get; set; }
        public virtual ICollection<TravEnt> TravEnts { get; set; }
    }
}
